name: RJThyme
favicon: null
layout_spectrum: 0.6856958430726081
typography_spectrum: 0.9828340143430978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#ffffff'
    - '#a09ddc'
    - '#135b4d'
    - '#f60d1a'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.9723060573451221
purpose: []
