name: RJThyme
favicon: null
layout_spectrum: 0.6856958430726081
typography_spectrum: 0.9828340143430978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.683178543113172
  lightness: 0.7624603388831019
  saturation: 0.1825756197795272
  rhythmicContrast: 0.9723060573451221
purpose: []
