name: RJThyme
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f1913'
    - '#97a344'
    - '#6e6b35'
    - '#373616'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.9723060573451221
purpose: []
