name: RJThyme
favicon: null
layout_spectrum: 0.70271
typography_spectrum: 0.55426
title: RJ Thyme
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#780a0b'
    - '#000000'
    - '#2f13c0'
    - '#9d9d9f'
    - '#e5defe'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
