title: RJ Thyme
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#0F1A1C'
    - '#1A2D31'
    - '#254145'
    - '#2E5157'
    - '#355D63'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: RJThyme
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.55426
layout_spectrum: 0.70271
