name: RJThyme
favicon: null
layout_spectrum: 0.70271
typography_spectrum: 0.55426
title: RJ Thyme
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#022940'
    - '#96daeb'
    - '#63a0c1'
    - '#4f6b7a'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
